name: Build APK for Kivy App

# Run the workflow on pushes to the main branch or on pull requests
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout the repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y python3-pip openjdk-11-jdk libffi-dev libssl-dev

    - name: Install Buildozer and Cython
      run: |
        pip install --upgrade pip setuptools
        pip install buildozer cython

    - name: Build the APK using Buildozer
      run: |
        buildozer android debug

    - name: List APK files
      run: ls -al bin/

    - name: Upload APK Artifact
      uses: actions/upload-artifact@v3
      with:
        name: kivy-apk
        path: bin/*.apk

